#!/bin/bash
date
echo rev4
echo installing python_pip
sudo apt-get install python-dev python-pip
echo installing WiringPi2
sudo pip install wiringpi2
echo installing IdleX
sudo pip install idlex
echo installing tightvnc
sudo apt-get install tightvncserver
