#!/bin/bash
date
echo rev3
echo updating system software - update
sudo apt-get update
echo updating system software - upgrade
sudo apt-get upgrade
echo installing python_pip
sudo apt-get install python-dev python-pip
echo installing WiringPi2
sudo pip install wiringpi2
echo installing IdleX
sudo pip install idlex
